config/routes.rb
Rails.application.routes.draw do
  
 
  
  resources :comments

  devise_for :users
  resources :picks do
    member do
      put "like", to: "picks#upvote"
      put "dislike", to: "picks#downvote"
    end
    resources :comments
  end
  resources :users do
    resource :profile
  end
  get '/home' => 'picks#home'
  root 'picks#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
    has_many :picks
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :pick
end

app/models/pick.rb
class Pick < ActiveRecord::Base
    acts_as_votable
    belongs_to :user
    belongs_to :category
    has_many :comments
    #validates :idea, presence: true, length: { maximum: 140 } # ideas are stopped at 140 characters
    
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    
    belongs_to :user
    
   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
   validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :picks
  has_one :profile
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def edit
  end

  def create
    @pick = Pick.find(params[:pick_id])
    @comment = @pick.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @pick, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment)
  end

  def destroy
    @comment.destroy
    respond_with(@comment)
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:pick_id, :body, :user_id)
    end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_action :set_pick, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index,:home, :show]
 

  # GET /picks
  # GET /picks.json
  def index
    @picks = Pick.all.order("created_at DESC")
  end
  
  def home
    @picks = Pick.all.order("created_at DESC")
    @category_id = Category
  end

  # GET /picks/1
  # GET /picks/1.json
  def show
     
  end

  # GET /picks/new
  def new
    @pick = current_user.picks.build
  end

  # GET /picks/1/edit
  def edit
  
  end

  # POST /picks
  # POST /picks.json
  def create
    @pick = current_user.picks.build(pick_params)

    respond_to do |format|
      if @pick.save
        format.html { redirect_to @pick, notice: 'Pick was successfully created.' }
        format.json { render :show, status: :created, location: @pick }
      else
        format.html { render :new }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /picks/1
  # PATCH/PUT /picks/1.json
  def update
    respond_to do |format|
      if @pick.update(pick_params)
        format.html { redirect_to @pick, notice: 'Pick was successfully updated.' }
        format.json { render :show, status: :ok, location: @pick }
      else
        format.html { render :edit }
        format.json { render json: @pick.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /picks/1
  # DELETE /picks/1.json
  def destroy
    @pick.destroy
    respond_to do |format|
      format.html { redirect_to home_path, notice: 'Pick was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def upvote
    @pick = Pick.find(params[:id])
    @pick.upvote_by current_user
    redirect_to :back
  end
  
  def downvote
    @pick = Pick.find(params[:id])
    @pick.downvote_by current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pick
      @pick = Pick.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pick_params
      params.require(:pick).permit(:player, :idea, :category_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    before_action :authenticate_user!
    before_action :only_current_user
    
    def new
        #form where each user can fill out their own profile
        @user = User.find( params[:user_id] )
        @profile = Profile.new
    end
    
    def create
        @user = User.find( params[:user_id] )
        @profile = @user.build_profile(profile_params)
        if @profile.save
            flash[:success] = "Profile Updated!"
            redirect_to user_path( params[:user_id] )
        else
            render action: :new
        end
    end
    
    def edit
        @user = User.find( params[:user_id] )
        @profile = @user.profile
    end
    
    def update
        @user = User.find( params[:user_id] )
        @profile = @user.profile
        if @profile.update_attributes(profile_params)
            flash[:success] = "Profile Updated!"
            redirect_to user_path( params[:user_id] )
        else
            render action: :edit
        end
    end
    
    private
    def profile_params
        params.require(:profile).permit(:user_name, :avatar, :location, :favorite_team, :description, :strategy)
    end
    
    def only_current_user
        @user = User.find( params[:user_id] )
        redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find( params[:id] )
    end
        
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/comments/_comment.erb
<%= form_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="#"><%= comment.body %></p>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</small></p>
		</div>

		<div class="btn-group pull-right">
			<% if comment.user == current_user -%>
				<%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pick_id %><br>
    <%= f.number_field :pick_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Pick</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.pick_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pick:</strong>
  <%= @comment.pick_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Birdie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Oxygen:300' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Lato:700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto:700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
    <div class='container'>
      <div class="navbar-header" style="padding-top: 2px;">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        
        <div class="logo">
          <%= link_to image_tag('blurb-logos.png'), root_path  %>
        </div>
          
        
        
      </div>
      
      
 
      
    
      <div class="collapse navbar-collapse" id="main-nav-collapse">
        
        
        <ul class="nav navbar-nav navbar-right">
          
         
          
          <% if current_user %>
            <li><%= link_to "New Blurb",  new_pick_path, class: "my-profile" %></li>
            <li><%= link_to "My Profile",  user_path(current_user),class: "my-profile" %></li>
            <li><%= link_to "Sign Out",  destroy_user_session_path, method: :delete, class: "sign-out" %></li>
           <% else %>
             <li><%= link_to "Join",  new_user_registration_path, {:style=> "color: black;font-size: 15px;border: 1px solid black; background: rgba(0,0,0,0); padding: 10px 25px 10px 25px;text-decoration: none;margin-top: 10px;"}  %></li>
             <li><%= link_to "Sign In", new_user_session_path,  {:style=> "color:black; font-size:15px;padding: 10px 20px 10px 20px; margin-top: 10px;"} %> </li>
          <% end %>
           
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
  </nav>
  
  
  
  
  
  
  <div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>
</div>

</body>
</html>

app/views/picks/_form.html.erb
<%= form_for(@pick) do |f| %>
  <% if @pick.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pick.errors.count, "error") %> prohibited this pick from being saved:</h2>

      <ul>
      <% @pick.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :choose_team %><br>
    <%= f.collection_select :category_id, Category.all, :id, :team, { promt: "Choose a Team" } %>
  </div>

  <div class="field">
    <%= f.label :player %><br>
    <%= f.text_field :player %>
  </div>
  <div class="field">
    <%= f.label :share_a_draft_pick_or_idea %><br>
    <%= f.text_area :idea %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/picks/edit.html.erb
    <h1>Editing pick</h1>
    
    <%= render 'form' %>


<%= link_to 'Show', @pick %> |
<%= link_to 'Back', picks_path %>

app/views/picks/home.html.erb
<!--<div class="text-center"> -->

<div class="container">
  <div class="row">
    <div class="text-center main-line">
      <h1><i class="fa fa-comments"></i> LATEST BLURBS</h1>
    </div>
    <div class="col-md-8">     
      <%  @picks.each do |pick| %>
        <%= content_tag(:div, class: 'well col-md-6 col-md-offset-6') do %>
          <%= content_tag(:div, class: 'teams') do %>
            <%= pick.category.team %>
          <% end %>
          
          <%= content_tag(:div, class: 'players') do %>
            <%= pick.player %></br>
          <% end %>
          
          <%= content_tag(:div, class: 'ideas') do %>
            <%= pick.idea %></br>
          <% end %>
          
          <div class="text-center">
            <div class="btn-group">
                                      
              <%= link_to like_pick_path(pick), method: :put, class: "btn btn-success btn-sm" do %>
                <i class="fa fa-thumbs-up"></i>
                <%= pick.get_upvotes.size %>
              <% end %>
              
              <%= link_to dislike_pick_path(pick), method: :put, class: "btn btn-danger btn-sm" do %>
                <i class="fa fa-thumbs-down"></i>
                <%= pick.get_downvotes.size %>
              <% end %>
                                        
              <%= link_to 'Comment', pick , class: "btn btn-primary btn-sm" %>
            </div>
          </div>
                            
          <%= content_tag(:div, class: 'text-right') do %>  
            <% if pick.user == current_user %>
            
              <%= link_to edit_pick_path(pick) do %>
                <i class="fa fa-pencil"></i>
              <% end %>
              
              <%= link_to pick, method: :delete, data: { confirm: 'Are you sure you want to DELETE this?' } do %>
                <i class="fa fa-trash"></i>
              <% end %>
            <% end %>
          <% end %>
                            
        <% end %>
      <% end %>
    </div>
    
    <div class="well col-md-3 spotty">
        <span class="trending-teams">Trending by TEAMS</span>
          <div class="dropdown">
            <button class="btn btn-ruff dropdown-toggle" type="button" data-toggle="dropdown">Teams
            <span class="caret"></span></button>
            <ul class="dropdown-menu">
              <% Category.all.each do |category| %>
            <li><%= link_to category.team, picks_path(category: category.team), class: "text-center" %></li>
            <% end %>
            </ul>
          </div>
        </div>  
      
      
  </div>
</div>

      
  

app/views/picks/index.html.erb
    
    <% if user_signed_in? %>
       <!-- show edit profile links and other streaming stuff
        -->
        <% if current_user.profile %>
            <%= link_to "Edit your profile", edit_user_profile_path(current_user) %>
            <%= link_to "View your profile", user_path(current_user) %>
                <!--<div class="text-center"> -->
           <!--<div class="text-center"> -->
        <div class="text-center">
          <h1>LATEST BLURBS</h1>
        </div>
    
  
  </br>
  
  
  
  <%  @picks.each do |pick| %>
    <%= content_tag(:div, class: 'well col-md-4 col-md-offset-4') do %>
      
        
        <%= content_tag(:div, class: 'teams') do %>
         <%= pick.category.team %>
        <% end %>
        <%= content_tag(:div, class: 'players') do %>
          <%= pick.player %></br>
        <% end %>
        <%= content_tag(:div, class: 'ideas') do %>
          <%= pick.idea %></br>
        <% end %>
                  <div class="text-center">
                    <div class="btn-group">
                      
      
                        <%= link_to like_pick_path(pick), method: :put, class: "btn btn-success btn-sm" do %>
                          <i class="fa fa-thumbs-up"></i>
                          
                          <%= pick.get_upvotes.size %>
                        <% end %>
                        <%= link_to dislike_pick_path(pick), method: :put, class: "btn btn-danger btn-sm" do %>
                          <i class="fa fa-thumbs-down"></i>
                          
                          <%= pick.get_downvotes.size %>
                          
                        <% end %>
                        
                        
                        <%= link_to 'Comment', pick , class: "btn btn-primary btn-sm" %>
        
                    </div>
                  </div>
                     
                     
        
         
        
        <%= content_tag(:div, class: 'text-right') do %>  
            <% if pick.user == current_user %>

                <%= link_to edit_pick_path(pick) do %>
                <i class="fa fa-pencil"></i>
                <% end %>
                
                <%= link_to pick, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="fa fa-trash"></i>
                <% end %>
        
            <% end %>
        <% end %>
            
        
        
    <% end %>
      
  <% end %>
  



  
        <% else %>
           <%= link_to "Create your profile", new_user_profile_path(current_user) if current_user %>
        <% end %>
          
   <% else %>

    <!-- If the user is not signed in, we show signup links and everything below 
    -->
<body div class="hello">
    
    <div class="move-up">
        <div class="inline">
                <div class="col-md-8 col-md-offset-2 text-center">
                    
                    <div class="main-line"><span>TAP</span> INTO THE <span>PULSE</span> OF THE BEST <span>FANTASY PICKS</span></div>
                    
                    <span style="font-family: 'lato', sans-serif;font-size: 25px;color: black;">Find out what real drafters are saying about</br> your fantasy picks right now</span></br></br>
                    <%= link_to "SIGN UP", "#", class: 'btn btn-default styler' %> </br>
                    
                    
                 
                </div>
        </div>
    </div>

<!--
<h2>REAL TIME INSIGHTS</h1>
<p>See what teams and players are trending</p>

<h2>COLLABORATE AND WIN</h2>
<p>The future of drafting is social. Connect with other active drafties before making your next trade. Find and follow the pros.</p>

<h2>GET IT ON THE GO MOBILE FRIENDLY</h2>
-->
    <% end %>
</div>


    

app/views/picks/new.html.erb
<div class="text-center main-line">
    <h1>NEW BLURB</h1>
</div>

<div class='well col-md-4 col-md-offset-4'</div>
        
    <%= render 'form' %>
        
    <%= link_to 'Back', root_path %>
    
</div>

app/views/picks/show.html.erb
    <div class="container">
    <p id="notice"><%= notice %></p>
    </div>
    
  
      <div class="well col-md-4 col-md-offset-4">
        
        <%= content_tag(:div, class: 'teams') do %>
          <h1> <%= @pick.category.team %> </h1>
        <% end %>
        
        <%= content_tag(:div, class: 'players') do %>
          <p> <%= @pick.player %> </p>
        <% end %>
        
        <%= content_tag(:div, class: 'ideas') do %>
          <p> <%= @pick.idea %> </p>
        <% end %>
      
          <div class="text-center">
            <div class="btn-group">
      
                <%= link_to like_pick_path(@pick), method: :put, class: "btn btn-success btn-sm" do %>
                  <i class="fa fa-thumbs-up"></i>
                    
                  <%= @pick.get_upvotes.size %>
                  
                <% end %>
                
                <%= link_to dislike_pick_path(@pick), method: :put, class: "btn btn-danger btn-sm" do %>
                  <i class="fa fa-thumbs-down"></i>
                  
                  <%= @pick.get_downvotes.size %>
                <% end %>
                
            </div>
          </div>
        </div>
  
  
<div class="col-md-4 col-md-offset-4">                   
    <h3 class="comments_title">
      <%= @pick.comments.count %> Comments
    </h3>
                    
    <div id="comments">
      <%= render :partial => @pick.comments %>
    </div>
                      
    <% if current_user %>
      <%= form_for [@pick, Comment.new]  do |f| %>
      <div class="field">
      <%= f.text_area :body, class: "form-control" %>
      </div>
    <br>
      <%= f.submit "Add Comment", class: "btn btn-primary" %>
      <% end %>
      <%= link_to 'Edit', edit_pick_path(@pick) %> 
      <%= link_to 'Back', home_path %>
    <% else %>
      <%= link_to "JOIN ", "#", class: 'btn btn-primary' %>
      <%= link_to "SIGN IN", "#", class: 'btn btn-primary' %>
    <% end %>
    
 
  
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %> 

        <div class="form-group">
          <%= f.label :user_name %>
          <%= f.text_field :user_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :avatar %>
          <%= f.file_field :avatar, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :location %>
          <%= f.text_field :location, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :favorite_team %>
          <%= f.text_field :favorite_team, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :Bio %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :strategy %>
          <%= f.select :strategy, ['Get the most expensive players', 'Look for Diamonds in the rough'], {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Profile", class: 'btn btn-primary' %>
        </div>
<% end %>
 

app/views/profiles/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Edit Your Profile</h1>
    <p class="text-center">Fill out your profile and be part of the Fantasy Feeds community!</p>
    <div class="well">
        <%= render 'form' %>
    </div>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <p class="text-center">Fill out your profile and be part of the Fantasy Feeds community!</p>
    <div class="well">
      <%= form_for @profile, url: user_profile_path do |f| %>
        <div class="form-group">
          <%= f.label :user_name %>
          <%= f.text_field :user_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :location %>
          <%= f.text_field :location, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :favorite_team %>
          <%= f.text_field :favorite_team, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :Bio %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :strategy %>
          <%= f.select :strategy, ['Get the most expensive players', 'Look for Diamonds in the rough'], {}, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Profile", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-3 text-center">
        
        <%= image_tag @user.profile.avatar.url %>
        <h1><%= @user.profile.user_name %></h1>
        <% if current_user.profile %>
            <%= link_to "Edit Profile", edit_user_profile_path(current_user) %>
        <% end %>
    </div>
    <div class="col-md-5 well">
        <h3>Location:</h3>
        <h4><%= @user.profile.location %></h4>
        <h3>Favorite Team:</h3>
        <h4><%= @user.profile.favorite_team %></h4>
        <h3> Bio: </h3>
        <h4><%= @user.profile.description %></h4>
        <h3> Drafting Strategy: </h3>
        <h4><%= @user.profile.strategy %></h4>
    </div>
</div>